### ISSUE TITLE
Some missing things

### ISSUE THREAD

**Issue by thewibbler** [woofbarkmeow/woofbarkmeow.github.io#1]
* No navbar on STEM page
* Empty Film and TV page - suggest putting an "under construction" page with link to main WBM page
* Empty Youtube page

**Comment by thewibbler** [comment]
Check out this https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by woofbarkmeow** [comment]
I have fixed the issues, but have not customised the 404 (i will soon).

**Comment by thewibbler** [comment]
It looks good, don't worry about the 404.html. 
Well done using the redirect to solve the problem instead.
